var value_a = "Dubai";
var value_b = "Dubai";
var value_c = "Abu Dhabi";
console.log("'value_a == value_b',they both are Dubai");
console.log(value_a == value_b);
console.log("'value_a == value_c',they both are Dubai");
console.log(value_a == value_c);
console.log("value_c is" + " " + value_c);
console.log("'value_a != value_c',they both of the are not Dubai");
console.log(value_a != value_c);
console.log("value_c is" + " " + value_c);
